<?php

/**
 * @file
 * Makes the review button on the Ubercart checkout page optional (set by store admin).
 *
 * Original author: Oliver Coleman, oliver@e-geek.com.au
 */

/**
 * Implementats hook_form_FORM_ID_alter().
 */
function uc_optional_checkout_review_form_uc_cart_checkout_settings_form_alter(&$form, &$form_state, $form_id) {
  $form['checkout']['uc_optional_checkout_review'] = array(
    '#type' => 'checkbox',
    '#title' => t('Skip checkout review'),
    '#default_value' => variable_get('uc_optional_checkout_review', FALSE),
  );
}

/**
 * Implementats hook_form_FORM_ID_alter().
 */
function uc_optional_checkout_review_form_uc_cart_checkout_form_alter(&$form, &$form_state, $form_id) {
  if (variable_get('uc_optional_checkout_review', FALSE)) {
    $form['#submit'][] = 'uc_optional_checkout_review_uc_cart_checkout_form_submit';
    $form['actions']['continue']['#value'] = t('Submit order');
  }
}

/**
 * Submit handler
 */
function uc_optional_checkout_review_uc_cart_checkout_form_submit($form, &$form_state) {
  if (variable_get('uc_optional_checkout_review', FALSE)) {
    $order = uc_order_load($_SESSION['cart_order']);
	$payment_method = $form_state['values']['panes']['payment']['payment_method'];
    if ($payment_method == 'paypal_wps') {
      $wps_form = drupal_retrieve_form('uc_paypal_wps_form', $form_state, $order);
      drupal_prepare_form('uc_paypal_wps_form', $wps_form, $form_state, $order);
      $wps_url = $wps_form['#action'] . '?';
      foreach (element_children($wps_form) as $key) {
        $wps_url .= urlencode($key) . '=' . urlencode($wps_form[$key]['#value']) . '&';
      }
      $wps_url = trim($wps_url, '&');
      drupal_goto($wps_url);
    } elseif ($payment_method == 'liqpay') {
		//dsm($form_state);
       $form_state['values']['op'] = t('Submit order');
	   $_SESSION['uc_liqpay_currency'] = 'UAH';
      drupal_form_submit('uc_liqpay_submit_form', $form_state, $order);
      $form_state['programmed'] = FALSE;
	} elseif ($payment_method == 'platon') {
      $form_state['values']['op'] = t('Submit order');
      drupal_form_submit('uc_platon_form', $form_state, $order);
      $form_state['programmed'] = FALSE;
	} else {
      $form_state['values']['op'] = t('Submit order');
      $form_state['uc_order'] = $order;
      drupal_form_submit('uc_cart_checkout_review_form', $form_state);
      $form_state['programmed'] = FALSE;
    }
  }
}
